import { Theme } from "@/app/services/ThemeService/types"
import { ThemeColors } from "./types"

export function alpha(hex: string, a: number): string {
    const base = hex.slice(0, 7)
    return base + Math.round(a * 255).toString(16).padStart(2, '0')
}

export function buildThemeJson(t: Theme & ThemeColors) {
    return {
        $schema: 'vscode://schemas/color-theme',
        name: t.name,
        type: 'dark',
        colors: {
            // Editor
            'editor.background': t.background,
            'editor.foreground': t.foreground,
            'editorLineNumber.foreground': t.mutedForeground,
            'editorLineNumber.activeForeground': t.foreground,
            'editorCursor.foreground': t.accent,
            'editor.selectionBackground': alpha(t.accent, 0.35),
            'editor.selectionHighlightBackground': alpha(t.accent, 0.2),
            'editor.wordHighlightBackground': alpha(t.h2, 0.2),
            'editor.wordHighlightStrongBackground': alpha(t.h3, 0.2),
            'editor.findMatchBackground': alpha(t.h1, 0.5),
            'editor.findMatchHighlightBackground': alpha(t.foreground, 0.25),
            'editor.lineHighlightBorder': t.border,
            'editor.rangeHighlightBackground': alpha(t.accent, 0.08),
            'editorWhitespace.foreground': alpha(t.foreground, 0.1),
            'editorIndentGuide.background1': alpha(t.foreground, 0.1),
            'editorIndentGuide.activeBackground1': alpha(t.foreground, 0.27),
            'editorRuler.foreground': alpha(t.foreground, 0.1),
            'editorCodeLens.foreground': t.mutedForeground,
            'editorBracketHighlight.foreground1': t.foreground,
            'editorBracketHighlight.foreground2': t.h1,
            'editorBracketHighlight.foreground3': t.h2,
            'editorBracketHighlight.foreground4': t.h3,
            'editorBracketHighlight.foreground5': t.accent,
            'editorBracketHighlight.foreground6': t.accentElevated,
            'editorLink.activeForeground': t.h2,
            'editorError.foreground': '#f87171',
            'editorWarning.foreground': t.h2,
            // Tabs & groups
            'editorGroup.border': t.accent,
            'editorGroup.dropBackground': alpha(t.border, 0.44),
            'editorGroupHeader.tabsBackground': t.surface,
            'tab.activeBackground': t.background,
            'tab.activeForeground': t.foreground,
            'tab.activeBorderTop': alpha(t.accent, 0.5),
            'tab.inactiveBackground': t.surface,
            'tab.inactiveForeground': t.mutedForeground,
            'tab.border': t.surfaceElevated,
            // General UI
            'foreground': t.foreground,
            'focusBorder': alpha(t.accent, 0.6),
            'selection.background': t.accent,
            'errorForeground': '#f87171',
            // Buttons
            'button.background': t.border,
            'button.foreground': t.foreground,
            'button.hoverBackground': t.surfaceElevated,
            'button.secondaryBackground': t.background,
            'button.secondaryForeground': t.foreground,
            'button.secondaryHoverBackground': t.surfaceElevated,
            // Dropdowns & inputs
            'dropdown.background': t.surfaceElevated,
            'dropdown.border': t.surface,
            'dropdown.foreground': t.foreground,
            'input.background': t.background,
            'input.foreground': t.foreground,
            'input.border': t.surface,
            'input.placeholderForeground': t.mutedForeground,
            'inputOption.activeBorder': t.accent,
            'inputValidation.errorBorder': '#f87171',
            'inputValidation.warningBorder': t.accentElevated,
            'inputValidation.infoBorder': t.h1,
            // Badges
            'badge.foreground': t.foreground,
            'badge.background': t.border,
            'progressBar.background': t.h1,
            // Lists
            'list.activeSelectionBackground': t.border,
            'list.activeSelectionForeground': t.foreground,
            'list.dropBackground': t.border,
            'list.focusBackground': alpha(t.border, 0.46),
            'list.highlightForeground': t.h2,
            'list.hoverBackground': alpha(t.border, 0.46),
            'list.inactiveSelectionBackground': alpha(t.border, 0.46),
            'list.warningForeground': t.accentElevated,
            'list.errorForeground': '#f87171',
            // Activity bar
            'activityBar.background': t.surfaceElevated,
            'activityBar.foreground': t.foreground,
            'activityBar.inactiveForeground': t.mutedForeground,
            'activityBar.activeBorder': alpha(t.h1, 0.5),
            'activityBar.activeBackground': alpha(t.accent, 0.06),
            'activityBarBadge.background': t.h1,
            'activityBarBadge.foreground': t.foreground,
            // Side bar
            'sideBar.background': t.surface,
            'sideBarTitle.foreground': t.foreground,
            'sideBarSectionHeader.background': t.background,
            'sideBarSectionHeader.border': t.surface,
            // Widgets
            'editorWidget.background': t.surface,
            'editorSuggestWidget.background': t.surface,
            'editorSuggestWidget.foreground': t.foreground,
            'editorSuggestWidget.selectedBackground': t.border,
            'editorHoverWidget.background': t.background,
            'editorHoverWidget.border': t.mutedForeground,
            'editorMarkerNavigation.background': t.surface,
            // Peek view
            'peekView.border': t.border,
            'peekViewEditor.background': t.background,
            'peekViewEditor.matchHighlightBackground': alpha(t.h3, 0.5),
            'peekViewResult.background': t.surface,
            'peekViewResult.fileForeground': t.foreground,
            'peekViewResult.lineForeground': t.foreground,
            'peekViewResult.matchHighlightBackground': alpha(t.h3, 0.5),
            'peekViewResult.selectionBackground': t.border,
            'peekViewResult.selectionForeground': t.foreground,
            'peekViewTitle.background': t.surface,
            'peekViewTitleDescription.foreground': t.mutedForeground,
            'peekViewTitleLabel.foreground': t.foreground,
            // Panel
            'panel.background': t.background,
            'panel.border': t.accent,
            'panelTitle.activeBorder': t.h1,
            'panelTitle.activeForeground': t.foreground,
            'panelTitle.inactiveForeground': t.mutedForeground,
            // Status bar
            'statusBar.background': t.surface,
            'statusBar.foreground': t.foreground,
            'statusBar.noFolderBackground': t.surface,
            'statusBar.noFolderForeground': t.foreground,
            'statusBarItem.prominentBackground': '#f87171',
            'statusBarItem.remoteForeground': t.background,
            'statusBarItem.remoteBackground': t.accent,
            // Title bar
            'titleBar.activeBackground': t.surfaceElevated,
            'titleBar.activeForeground': t.foreground,
            'titleBar.inactiveBackground': t.surfaceElevated,
            'titleBar.inactiveForeground': t.mutedForeground,
            // Breadcrumbs
            'breadcrumb.foreground': t.mutedForeground,
            'breadcrumb.background': t.background,
            'breadcrumb.focusForeground': t.foreground,
            'breadcrumb.activeSelectionForeground': t.foreground,
            'breadcrumbPicker.background': t.surface,
            // Terminal
            'terminal.background': t.background,
            'terminal.foreground': t.foreground,
            'terminal.ansiBlack': t.surface,
            'terminal.ansiRed': '#f87171',
            'terminal.ansiGreen': t.h2,
            'terminal.ansiYellow': t.h3,
            'terminal.ansiBlue': t.accent,
            'terminal.ansiMagenta': t.h1,
            'terminal.ansiCyan': t.accentElevated,
            'terminal.ansiWhite': t.foreground,
            'terminal.ansiBrightBlack': t.mutedForeground,
            'terminal.ansiBrightRed': '#fca5a5',
            'terminal.ansiBrightGreen': t.h2,
            'terminal.ansiBrightYellow': t.h3,
            'terminal.ansiBrightBlue': t.accentElevated,
            'terminal.ansiBrightMagenta': t.h1,
            'terminal.ansiBrightCyan': t.accentElevated,
            'terminal.ansiBrightWhite': '#ffffff',
            // Git
            'gitDecoration.modifiedResourceForeground': t.h2,
            'gitDecoration.deletedResourceForeground': '#f87171',
            'gitDecoration.untrackedResourceForeground': t.h3,
            'gitDecoration.ignoredResourceForeground': t.mutedForeground,
            'gitDecoration.conflictingResourceForeground': t.accentElevated,
            // Diff
            'diffEditor.insertedTextBackground': alpha(t.h2, 0.12),
            'diffEditor.removedTextBackground': alpha('#f87171', 0.32),
            // Gutter
            'editorGutter.modifiedBackground': alpha(t.h2, 0.5),
            'editorGutter.addedBackground': alpha(t.h3, 0.5),
            'editorGutter.deletedBackground': alpha('#f87171', 0.5),
            // Overview ruler
            'editorOverviewRuler.border': t.surface,
            'editorOverviewRuler.modifiedForeground': alpha(t.h2, 0.5),
            'editorOverviewRuler.addedForeground': alpha(t.h3, 0.5),
            'editorOverviewRuler.deletedForeground': alpha('#f87171', 0.5),
            'editorOverviewRuler.errorForeground': alpha('#f87171', 0.5),
            'editorOverviewRuler.warningForeground': alpha(t.accentElevated, 0.5),
            // Merge
            'merge.currentHeaderBackground': alpha(t.h3, 0.56),
            'merge.incomingHeaderBackground': alpha(t.accent, 0.56),
            // Picker / filter
            'pickerGroup.border': t.accent,
            'pickerGroup.foreground': t.h2,
            'listFilterWidget.background': t.surfaceElevated,
            'listFilterWidget.outline': t.border,
            'listFilterWidget.noMatchesOutline': '#f87171',
            // Debug
            'debugToolBar.background': t.surface,
            // Settings
            'settings.headerForeground': t.foreground,
            'settings.modifiedItemIndicator': t.accentElevated,
            'settings.dropdownBackground': t.surface,
            'settings.dropdownForeground': t.foreground,
            'settings.dropdownBorder': t.surface,
            'settings.checkboxBackground': t.surface,
            'settings.checkboxForeground': t.foreground,
            'settings.checkboxBorder': t.surface,
            'settings.textInputBackground': t.surface,
            'settings.textInputForeground': t.foreground,
            'settings.textInputBorder': t.surface,
            'settings.numberInputBackground': t.surface,
            'settings.numberInputForeground': t.foreground,
            'settings.numberInputBorder': t.surface,
        },
        tokenColors: [
            { name: 'Comments',             scope: ['comment', 'punctuation.definition.comment'],                                                                                                                                       settings: { foreground: t.mutedForeground } },
            { name: 'Strings',              scope: ['string'],                                                                                                                                                                          settings: { foreground: t.h3 } },
            { name: 'String quotes',        scope: ['punctuation.definition.string.begin', 'punctuation.definition.string.end'],                                                                                                        settings: { foreground: t.h3 } },
            { name: 'Keywords',             scope: ['keyword', 'punctuation.definition.keyword', 'storage.modifier'],                                                                                                                   settings: { foreground: t.h1 } },
            { name: 'Storage',              scope: ['storage'],                                                                                                                                                                         settings: { foreground: t.h1, fontStyle: 'regular' } },
            { name: 'Types',                scope: ['entity.name.type', 'storage.type', 'keyword.type.cs', 'source.go storage.type'],                                                                                                   settings: { foreground: t.h2, fontStyle: 'italic' } },
            { name: 'Classes',              scope: ['entity.name.type.class', 'entity.name.class'],                                                                                                                                     settings: { foreground: t.h2, fontStyle: 'normal' } },
            { name: 'Functions',            scope: ['entity.name.function', 'meta.function-call.object', 'support.function'],                                                                                                           settings: { foreground: t.h3 } },
            { name: 'Constants',            scope: ['constant', 'variable.other.constant'],                                                                                                                                             settings: { foreground: t.accent } },
            { name: 'Variables',            scope: ['variable', 'support.variable.property'],                                                                                                                                           settings: { foreground: t.foreground } },
            { name: 'Parameters',           scope: ['variable.parameter', 'entity.name.variable.parameter'],                                                                                                                            settings: { foreground: t.accentElevated, fontStyle: 'italic' } },
            { name: 'HTML tags',            scope: ['entity.name.tag'],                                                                                                                                                                 settings: { foreground: t.h1 } },
            { name: 'HTML/CSS attributes',  scope: ['entity.other.attribute-name'],                                                                                                                                                     settings: { foreground: t.h3, fontStyle: 'italic' } },
            { name: 'CSS selectors',        scope: ['meta.selector', 'support.type.property-name'],                                                                                                                                     settings: { foreground: t.h1 } },
            { name: 'Numbers',              scope: ['constant.numeric'],                                                                                                                                                                settings: { foreground: t.accent } },
            { name: 'Booleans',             scope: ['constant.language'],                                                                                                                                                               settings: { foreground: t.accent } },
            { name: 'Operators',            scope: ['keyword.operator'],                                                                                                                                                                settings: { foreground: t.h1 } },
            { name: 'Punctuation',          scope: ['punctuation', 'meta.brace.round'],                                                                                                                                                 settings: { foreground: t.foreground } },
            { name: 'Template expressions', scope: ['punctuation.definition.template-expression.begin', 'punctuation.definition.template-expression.end', 'punctuation.section.embedded'],                                             settings: { foreground: t.h1 } },
            { name: 'this / self',          scope: ['variable.language'],                                                                                                                                                               settings: { foreground: t.accent, fontStyle: 'italic' } },
            { name: 'RegExp',               scope: ['string.regexp'],                                                                                                                                                                   settings: { foreground: t.h3 } },
            { name: 'Markup headings',      scope: ['markup.heading'],                                                                                                                                                                  settings: { foreground: t.accent, fontStyle: 'bold' } },
            { name: 'Markup bold',          scope: ['markup.bold'],                                                                                                                                                                     settings: { foreground: t.accentElevated, fontStyle: 'bold' } },
            { name: 'Markup italic',        scope: ['markup.italic'],                                                                                                                                                                   settings: { foreground: t.h3, fontStyle: 'italic' } },
            { name: 'Markup inline code',   scope: ['markup.inline.raw'],                                                                                                                                                               settings: { foreground: t.h3 } },
            { name: 'Markup links',         scope: ['markup.underline.link'],                                                                                                                                                           settings: { foreground: t.h2 } },
            { name: 'Invalid',              scope: ['invalid'],                                                                                                                                                                         settings: { foreground: '#f87171', fontStyle: 'underline italic' } },
        ],
        semanticHighlighting: true,
        semanticTokenColors: {
            variable:           t.foreground,
            'variable.readonly': t.accent,
            parameter:          { foreground: t.accentElevated, fontStyle: 'italic' },
            property:           t.foreground,
            function:           t.h3,
            method:             t.h3,
            class:              t.h2,
            interface:          { foreground: t.h2, fontStyle: 'italic' },
            type:               { foreground: t.h2, fontStyle: 'italic' },
            enum:               t.h2,
            enumMember:         t.accent,
            namespace:          t.h2,
            keyword:            t.h1,
            modifier:           t.h1,
            comment:            t.mutedForeground,
            string:             t.h3,
            number:             t.accent,
            regexp:             t.h3,
            operator:           t.h1,
            decorator:          { foreground: t.h3, fontStyle: 'italic' },
        },
    }
}
